GE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views


app_name = 'core'
urlpatterns = [
    path('', views.Home, name='Home'),
    path('detail/<slug:slug>/', views.TournamentDetail, name='Detail'),
    path('register/<slug:slug>/', views.Register, name='Register'),
    path('payment/<payment_option>/', views.PaymentView, name='Payment'),
    path('cancel/', views.CancelRegisteration, name='Cancel'),
    path('contact/', views.ContactView, name='Contact'),
    path('<slug:slug>/teams/', views.AllTeams, name='Teams'),
    path('cancel-team/', views.CancelTeamRegisteration, name='Cancel-Team'),
    path('signup/', views.Signup, name='Signup'),
    path('login/', views.Login, name='Login'),
    path('logout/', views.Logout, name='Logout'),
]

templates/Login.html
{%extends 'base.html'%}
{% load static %}

{%block content%}


<style>
    input {
        margin-bottom: 20px;
        width: 90%;
        height: 30px;
        padding: .4%;
        border: none;
        border-bottom: 1px gray solid;
        font-size: 16px;
        letter-spacing: 1px;
        margin-bottom: 40px;
        text-align: center;
    }

    input:focus {
        border-bottom: 2px rgb(58, 0, 194) solid;
        outline: none;
    }

    .error {
        background-color: lightgreen;
        padding: 10px 20px;
        letter-spacing: 2px;
        font-size: 18px;
        color: black;
    }


    .container-1 {
        width: 100%;
    }

    .login_form {
        width: 60%;
        margin: auto;
    }

    .fee {
        font-size: 18px;
        color: rgb(89, 0, 255);
    }

    .primary_btn {
        width: 30%;
        margin-left: 30%;
    }

    .link {
        text-align: center;
    }

    .login {
        width: 30%;
        margin-left: 38%;
    }
</style>

<!--================Home Banner Area =================-->
<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background="">
        </div>
        <div class="container">
            <div class="banner_content text-center">
                <div class="page_link">
                    <a href="{% url 'core:Home' %}">Home</a>
                    <a href="{% url 'core:Login' %}">LOGIN</a>
                </div>
                <h2>LOGIN NOW</h2>

            </div>
        </div>
    </div>
</section>
<!--================End Home Banner Area =================-->
<div class="container-1">
    {%for message in messages%}
    <h6 class="error">{{message}}</h6>
    {%endfor%}
</div>
<!-- Login -->
<div class="container mt-5 mb-5 ml-auto mr-auto">
    <div class="login_form">
        <div class="title">
            <h1 class="mb-4 login">Login</h1>
        </div>
        <form action="" method="post">
            {% csrf_token %}
            <input type="text" name='un' placeholder="Username" autocomplete="off"><br>
            <input type="password" name='password' placeholder="Password" autocomplete="off"><br>
            <button type="submit" class="btn primary_btn">Login</button>
        </form>
        <p class="mt-4 link">Don't have an account? <a href="{% url 'core:Signup' %}" class="btn">Sign up</a></p>
    </div>
</div>

{%endblock%}

templates/Signup.html
{%extends 'base.html'%}
{% load static %}

{%block content%}
<style>
    input {
        margin-bottom: 20px;
        width: 90%;
        height: 30px;
        padding: .4%;
        border: none;
        border-bottom: 1px gray solid;
        font-size: 16px;
        letter-spacing: 1px;
        margin-bottom: 40px;
        text-align: center;
    }

    input:focus {
        border-bottom: 2px rgb(58, 0, 194) solid;
        outline: none;
    }

    .error {
        background-color: lightgreen;
        padding: 10px 20px;
        letter-spacing: 2px;
        font-size: 18px;
        color: black;
    }

    .container-1 {
        width: 100%;
    }

    .login_form {
        width: 60%;
        margin: auto;
    }

    .fee {
        font-size: 18px;
        color: rgb(89, 0, 255);
    }

    .primary_btn {
        width: 30%;
        margin-left: 30%;
    }

    .link {
        text-align: center;
    }

    .login {
        width: 30%;
        margin-left: 35%;
    }
</style>

<!--================Home Banner Area =================-->
<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background="">
        </div>
        <div class="container">
            <div class="banner_content text-center">
                <div class="page_link">
                    <a href="{% url 'core:Home' %}">Home</a>
                    <a href="{% url 'core:Signup' %}">SIGN UP</a>
                </div>
                <h2>SIGNUP NOW</h2>

            </div>
        </div>
    </div>
</section>
<!--================End Home Banner Area =================-->
<div class="container-1">
    {%for message in messages%}
    <h6 class="error">{{message}}</h6>
    {%endfor%}
</div>


<!-- Signup -->
<div class="container mt-5 mb-5">
    <div class="login_form">
        <div class="login mb-5">
            <h1>Sign up</h1>
        </div>
        <form action="" method="post">
            {% csrf_token %}
            <input type="text" name='name' placeholder="Name"><br>
            <input type="text" name='username' placeholder="Username"><br>
            <input type="email" name='email' placeholder="Email"><br>
            <input type="password" name='pass1' placeholder="Password"><br>
            <input type="password" name='pass2' placeholder="Confirm Password"><br>
            <button type="submit" class="btn primary_btn">Sign up</button>
        </form>
        <p class="link mt-4">Already have an account? <a href="{% url 'core:Login' %}" class="btn">Login</a></p>

    </div>
</div>

{%endblock%}

templates/base.html
{%load static%}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Ground Esports</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/linericon/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/nice-select/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/animate-css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/flaticon/flaticon.css' %}">
    <!-- main css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}"> {% block css %} {% endblock css %}
</head>

<body>

    <!--================Header Menu Area =================-->
    <header class="header_area">
        <div class="main_menu">
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="container">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <a class="navbar-brand logo_h" href="{% url 'core:Home' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                        <ul class="nav navbar-nav menu_nav justify-content-center">
                            <li class="nav-item active"><a class="nav-link" href="{% url 'core:Home' %}">Home</a></li>
                            {% block navitems %} {% endblock navitems %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'core:Contact' %}">Contact</a></li>

                            {% if request.user.is_authenticated %}
                            <li class="nav-item"><a href="{%  url 'core:Logout' %}" class="nav-link">Logout</a></li>
                            <li class="nav-item mt-auto mb-auto"><a href="#" class="btn btn-warning">Welcome,
                                    {{request.user.username}}</a></li>
                        </ul>
                        {% else %}
                        <ul class="nav navbar-nav navbar-right ml-5">
                            <li class="nav-item mt-auto mb-auto"><a href="{% url 'core:Signup' %}" class="btn btn-warning">Sign up</a>
                            </li>
                            <li class="nav-item mt-auto mb-auto"><a href="{% url 'core:Login' %}" class="btn btn-warning">Login</a>
                            </li>
                        </ul>
                        {% endif %}
                    </div>
                </div>
            </nav>
        </div>
    </header>
    <!--================Header Menu Area =================-->
    {% block content %} {%endblock%}


    <!--================Footer Area =================-->
    <footer class=" footer_area section_gap_top">
        <div class="container">
            <div class="row footer_inner">
                <div class="col-lg-4 col-sm-8">
                    <aside class="f_widget ab_widget">
                        <div class="f_title">
                            <h4>Follow Us</h4>
                        </div>
                        <ul>
                            <li>
                                <a href="#"></a>YouTube</a>
                            </li>
                            <li>
                                <a href="#"></a>Instagram</a>
                            </li>
                            <li>
                                <a href="#"></a>Facebook</a>
                            </li>
                            <li>
                                <a href="#"></a>Twitter</a>
                            </li>
                        </ul>
                    </aside>
                </div>
                <div class="col-lg-4 col-sm-8">
                    <aside class="f_widget ab_widget">
                        <div class="f_title">
                            <h4>Support</h4>
                        </div>
                        <ul>
                            <li>
                                <a href="#"></a>Documentation</a>
                            </li>
                            <a href="#">
                                <li>
                                    <a href="#"></a>Data Securiry
                            </a>
                            </li>
                            <li>
                                <a href="#"></a>Site Performance</a>
                            </li>
                            <li>
                                <a href="#"></a>Action Plan</a>
                            </li>
                            <li>
                                <a href="#"></a>Resources</a>
                            </li>
                        </ul>
                    </aside>
                </div>
                <div class="col-lg-4 col-sm-8">
                    <aside class="f_widget ab_widget">
                        <div class="f_title">
                            <h4>Legal</h4>
                        </div>
                        <ul>
                            <li>
                                <a href="#"></a>Terms and conditions</a>
                            </li>
                            <a href="#">
                                <li>
                                    <a href="#"></a>Privacy Policy
                            </a>
                            </li>
                            <li>
                                <a href="#"></a>Cookie Information</a>
                            </li>
                            <li>
                                <a href="#"></a>Opt - Out</a>
                            </li>
                        </ul>
                    </aside>
                </div>
            </div>
            <div class="row single-footer-widget">
                <div class="col-lg-6 col-md-6 col-sm-12">
                    <div class="copy_right_text">
                        <p>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>
                                document.write(new Date().getFullYear());
                            </script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a> and Developed by Kashif Mehmood
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-12">
                    <div class="social_widget">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                        <a href="#"><i class="fa fa-behance"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--================End Footer Area =================-->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/stellar.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'vendors/nice-select/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'vendors/isotope/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'vendors/isotope/isotope-min.js' %}"></script>
    <script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'vendors/counter-up/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'vendors/counter-up/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <!--gmaps Js-->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
    <script src="{% static 'js/gmaps.min.js' %}"></script>
    <script src="{% static 'js/theme.js' %}"></script>
</body>

</html>

templates/detail.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
{%for message in messages%}
<h6 class="error">{{message}}</h6>
{%endfor%}
<style>
    .container-1 {
        width: 60%;
        margin: 150px auto;
    }

    .container-1 span {
        color: rgb(132, 0, 255);
        font-weight: bold;
    }

    .product-title {
        color: black;
    }

    .subtitle {
        color: black;
        text-align: center;
        margin-top: 50px;
    }
</style>
<main>
    <!--================Home Banner Area =================-->
    <section class="banner_area">
        <div class="banner_inner d-flex align-items-center">
            <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0"
                data-background="">
            </div>
            <div class="container">
                <div class="banner_content text-center">
                    <div class="page_link">
                        <a href="{% url 'core:Home' %}">Home</a>
                        <a href="{{tournament.get_absolute_url}}">Tournament Detail</a>
                    </div>
                    <h2>Tournament DETAIL</h2>

                </div>
            </div>
        </div>
    </section>
    <!--================End Home Banner Area =================-->
    <div class="container-1">
        <img class="ml-auto mr-auto" src="{{tournament.image.url}}">
        <div class="details">
            <h3 class="product-title mt-4">{{tournament.title}}</h3>
            <p>{{tournament.description}}
            </p>
            <br>
            <p>Organizer: <span class="ml-5 pl-2">{{tournament.organizer}}</span></p>
            <p>Registeration Fee: <span class="ml-2">${{tournament.entry_fee}}</span></p>
            <p>Total Prize Pool : <span class="ml-3">${{tournament.prize_pool}}</span></p>
            <p>Format: <span class="ml-5 pl-4">TBD</span></p>
            <p>Last Date: <span class="ml-5 pl-2">{{tournament.last_date}}</span></p>
            <br><br>
            <div class="btns">
                <a class="primary_btn" href="{{tournament.get_registeration_url}}">Register Now</a>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

templates/index.html
{%extends 'base.html'%} {% load static %} {% block navitems %}
<li class="nav-item"><a class="nav-link" href="#About">About</a></li>
<li class="nav-item"><a class="nav-link" href="#Tournament">Tournament</a> {% endblock navitems %} {%block content%}



    <style>
        html {
            scroll-behavior: smooth;
        }
        
        .error {
            background-color: yellow;
            font-size: 18px;
            padding: 10px 20px;
            letter-spacing: 3px;
            color: black;
        }
        
        .container-1 {
            width: 100%;
            margin-top: 100px;
        }
    </style>

    </div>
    <!--================Home Banner Area =================-->
    <section class="home_banner_area">
        <div class="container-1">
            {% for message in messages %}
            <p class="error">{{ message }}</p>
            {% endfor %}
        </div>
        <div class="banner_inner">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="home_left_img">
                            <img class="img-fluid" src="{% static 'img/banner/home-left.png' %}">
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="banner_content">
                            <h2>
                                Pakistan's No 1 <br> Tournament organizing <br> management.
                            </h2>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temp or incididunt ut labore et dolore magna aliqua. Ut enim ad minim.
                            </p>
                            <div class="d-flex align-items-center">
                                <a id="play-home-video" class="video-play-button" href="https://www.youtube.com/watch?v=vParh5wE-tM">
                                    <span></span>
                                </a>
                                <div class="watch_video text-uppercase">
                                    watch the video
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================End Home Banner Area =================-->

    <!--================Start About Us Area =================-->
    <section class="about_us_area section_gap_top" id="About">
        <div class="container">
            <div class="row about_content align-items-center">
                <div class="col-lg-6">
                    <div class="section_content">
                        <h6>About Us</h6>
                        <h1>We Believe that <br>Interior beauty Lasts Long</h1>
                        <p>inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct standards especially in the workplace. That’s why it’s crucial that as women.</p>
                        <a class="primary_btn" href="#">Learn More</a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="about_us_image_box justify-content-center">
                        <img class="img-fluid w-100" src="{% static 'img/Pubg-1.jpg' %}">
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================End About Us Area =================-->

    <!--================First Upcoming Games Area =================-->
    {% if team %}
    <div class="container mt-5 bg-dark w-100 pt-3 pb-3 pl-auto pr-auto">

        <p style="color: white;
	 letter-spacing:2px;
	 font-size: 17px;">Please Pay your Registeration Fee to Register your team.</p>
        <a href="payment/hbl/" class="btn btn-warning">Pay Now</a>

    </div>
    {% endif %}

    <section class="upcoming_games_area" id="Tournament">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    {% if tournaments %}
                    <div class="main_title">
                        <h2>Tournament</h2>
                        <h1>Tournament</h1>
                    </div>
                    {% else %}
                    <div class="main_title">
                        <h2>No Tournament</h2>
                        <h1>No Tournament</h1>
                    </div>
                    {% endif %}
                </div>
            </div>

            {% if rt %}
            <div class="container mt-5 bg-dark w-100 pt-3 pb-3 pl-auto pr-auto">

                <p style="color: white;
			 letter-spacing:2px;
			 font-size: 17px;">Your Team is Registered in the Tournament.</p>
                <a href="{% url 'core:Cancel-Team' %}" class="btn btn-danger">Cancel Registeration</a> {% for t in tournaments %}
                <a href="{{t.slug}}/teams/" class="btn btn-primary ml-4">Check Registered Teams</a> {% endfor %}
            </div>


            {% else %}

            <div class="row text-center">
                {% for t in tournaments %}
                <div class="col-lg-5 col-md-6 col-sm-6 mb-5 ml-auto mr-auto">
                    <div class="new_games_item">
                        <img src="{{t.image.url}}">
                        <div class="upcoming_title">
                            <h3><a href="{{t.get_absolute_url}}">{{t.title}}</a></h3>

                        </div>
                    </div>
                    <a href="{{t.get_registeration_url}}" class="btn primary_btn">Register Now</a>
                </div>


                {% empty %}
                <h5 class="ml-auto mr-auto">Sorry, Currently there is no Tournament.</h5>
                {%endfor%}
            </div>
            {% endif %}
        </div>
    </section>
    <!--================End Upcoming Games Area =================-->





    <!--================ Start Frequently Asked Questions Area ================-->
    <section class="frequently_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="main_title">
                        <h2>Frequently Asked Questions</h2>
                        <h1>Frequently Asked Questions</h1>
                    </div>
                </div>
            </div>
            <div class="row frequent_inner">
                <div class="col-lg-5 col-md-5">
                    <div class="frequent_item">
                        <h3>We Believe that Interior beauty Lasts Long</h3>
                        <p>inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct standards especially in the workplace. That’s why it’s crucial that as women.</p>
                    </div>
                </div>
                <div class="offset-lg-2 col-lg-5 offset-md-2 col-md-5">
                    <div class="frequent_item">
                        <h3>We Believe that Interior beauty Lasts Long</h3>
                        <p>inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct standards especially in the workplace. That’s why it’s crucial that as women.</p>
                    </div>
                </div>
                <div class="col-lg-5 col-md-5">
                    <div class="frequent_item">
                        <h3>We Believe that Interior beauty Lasts Long</h3>
                        <p>inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct standards especially in the workplace. That’s why it’s crucial that as women.</p>
                    </div>
                </div>
                <div class="offset-lg-2 col-lg-5 offset-md-2 col-md-5">
                    <div class="frequent_item">
                        <h3>We Believe that Interior beauty Lasts Long</h3>
                        <p>inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct standards especially in the workplace. That’s why it’s crucial that as women.</p>
                    </div>
                </div>
                <div class="col-lg-5 col-md-5">
                    <div class="frequent_item last-child">
                        <h3>We Believe that Interior beauty Lasts Long</h3>
                        <p>inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct standards especially in the workplace. That’s why it’s crucial that as women.</p>
                    </div>
                </div>
                <div class="offset-lg-2 col-lg-5 offset-md-2 col-md-5">
                    <div class="frequent_item last-child">
                        <h3>We Believe that Interior beauty Lasts Long</h3>
                        <p>inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct standards especially in the workplace. That’s why it’s crucial that as women.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================ End Frequently Asked Questions Area ================-->


    <!--================ Start Newsletter Area ================-->
    <section class="newsletter_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-12">
                    <div class="newsletter_inner">
                        <h1>Subscribe Our Newsletter</h1>
                        <p>We won’t send any kind of spam</p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-12">
                    <aside class="newsletter_widget">
                        <div id="mc_embed_signup">
                            <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="subscribe_form relative">
                                <div class="input-group d-flex flex-row">
                                    <input name="EMAIL" placeholder="Enter email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Your email address'" required="" type="email">
                                    <button class="btn primary_btn">Subscribe</button>
                                </div>
                            </form>
                        </div>
                    </aside>
                </div>
            </div>
        </div>
    </section>
    <!--================ End Newsletter Area ================-->
    {%endblock%}

templates/payment.html
{%extends 'base.html'%}

{%block content%}

<style>
    input {
        margin-bottom: 20px;
        width: 90%;
        height: 30px;
        padding: .4%;
        border: none;
        border-bottom: 1px gray solid;
        font-size: 16px;
        letter-spacing: 1px;
        margin-bottom: 40px;
    }

    input:focus {
        border-bottom: 2px rgb(58, 0, 194) solid;
        outline: none;
    }

    .error {
        background-color: lightgreen;
        font-size: 18px;
        padding: 10px 20px;
        letter-spacing: 3px;
        color: black;
    }

    .container-1 {
        width: 100%;
    }

    .fee {
        font-size: 18px;
        color: rgb(89, 0, 255);
    }
</style>

<main class="pt-5">
    <section class="banner_area">
        <div class="banner_inner d-flex align-items-center">
            <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0"
                data-background="">
            </div>
            <div class="container">
                <div class="banner_content text-center">
                    <div class="page_link">
                        <a href="{% url 'core:Home' %}">Home</a>
                        <a href="\payment\hbl\">Payment</a>
                    </div>
                    <h2>PAY NOW</h2>

                </div>
            </div>
        </div>
    </section>

    <div class="container-1">
        <div class="container-1">
            {% for message in messages %}
            <p class="error">{{ message }}</p>
            {% endfor %}
        </div>
    </div>
    <div class="container mt-5 mb-5 pb-5">
        <div class="card-body w-100 mt-5 mb-5">
            <h3 class="card-text label">Pay Here</h3><br>
            <form action="." method="post">
                {%csrf_token%}
                <input type="text" name="card" placeholder="Card Number"><br>
                <h5 class="fee">Please Pay $<span class="fee"> {{teams}}</span></h5><br>
                <button class="btn primary_btn" type="submit">Pay</button>
                <a href="{% url 'core:Cancel' %}" class="btn btn-default ml-4">Cancel</a>
            </form>
        </div>
    </div>
</main>

{%endblock%}